language: java
jdk: oraclejdk8

services:
  - docker

script:
  - ./mvnw clean install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=akshayrajvanshi1992/sortmeup
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t sortmeup .
  - docker tag sortmeup $REPO:$TAG
  - docker push $REPO:$TAG