language: java
jdk: oraclejdk8

services:
  - docker

script:
  - ./mvnw clean install

env:
  - travis encrypt DOCKER_USER=”akspri2730”
  - travis encrypt DOCKER_PASS=”akshay1992”

after_success:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
      - export IMAGE_NAME=akspri2730/sortmeup
      - docker build -t $IMAGE_NAME:$COMMIT .
      - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
      - docker push $IMAGE_NAME